# -*- coding: utf-8 -*-
"""app1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KPGQNmCzYS2jYRmqsqOFKCkw6COyJ_o2
"""

import streamlit as st
import joblib
import numpy as np

# Load the model
def load_model(file_path):
    return joblib.load(file_path)

# Main application
def main():
    # Load Model 1
    model_1 = load_model('model_1d.pkl')

    # Application title and layout
    st.title("Model 1: Multioutput Regression")
    st.write("This application predicts yield based on input parameters using Model 1.")

    # Input fields for user interaction
    st.header("Input Fields for Yield Prediction")
    yield_min = st.number_input("Yield Min:", min_value=1000.0, max_value=3000.0, value=1000.0)
    yield_max = st.number_input("Yield Max:", min_value=3000.0, max_value=4000.0, value=3000.0)

    # Predict and display results
    if st.button("Predict Yield"):
        # Prepare input data
        input_data = np.array([[yield_min, yield_max]])

        # Debug: Display the input shape
        st.write(f"Input Shape: {input_data.shape}")
        st.write(f"Input Data: {input_data}")

        try:
            prediction = model_1.predict(input_data)
            st.success(f"Predicted Yield: {prediction[0]}")
        except Exception as e:
            st.error(f"An error occurred during prediction: {e}")

# Run the application
if __name__ == "__main__":
    main()
